name: Deploy React App

on:
  push:
    branches:
      - test # Or your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use your preferred Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Build Docker Image
        run: docker build -t your-dockerhub-username/convogene-ui .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push gyash99/convogene-ui
